name: Haskell CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: haskell-actions/setup@v2 
      id: cabal-setup
      with:
        ghc-version: '9.8.2'
        cabal-version: '3.6.2.0'

    - name : Configure cabal
      run : |
        cabal configure --enable-tests --enable-benchmarks --disable-documentation
        cabal build all --dry-run

    - name: Cache
      uses: actions/cache/restore@v4
      id: cache
      env:
        key: ${{ runner.os }}-ghc-${{ steps.setup.outputs.ghc-version }}-cabal-${{ steps.setup.outputs.cabal-version }}
      with:
        path: ${{ steps.cabal-setup.outputs.cabal-store }}
        key: ${{ env.key }}-plan-${{ hashFiles('**/plan.json') }}
        restore-keys: ${{ env.key }}-

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        cabal build --only-dependencies

    - name: Save cached dependencies
      uses: actions/cache/save@v4
      # If we had an exact cache hit, trying to save the cache would error because of key clash.
      if: steps.cache.outputs.cache-hit != 'true'
      with:
        path: ${{ steps.cabal-setup.outputs.cabal-store }}
        key: ${{ steps.cache.outputs.cache-primary-key }}
    - name : Run Tests
      run: ${{steps.cabal-setup.outputs.cabal-exe}} test
    - name: Build
      run: cabal build hapl --ghc-options=-O2
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        # Artifact name
        name: ${{ matrix.os }}-hapl # optional, default is github-pages
        # Path of the directory containing the static assets.
        path: | # default is _site/
          dist-newstyle/build/*/*/*/*/hapl/build/hapl/hapl
          dist-newstyle/build/*/*/*/*/hapl/build/hapl/hapl.exe
        # Duration after which artifact will expire in days.
        retention-days: 90 # optional, default is 1
