name: Haskell CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: haskell-actions/setup@v2 
      id: cabal-setup
      with:
        ghc-version: '9.8.2'
        cabal-version: '3.6.2.0'

    - name: Cache
      uses: actions/cache@v3
      env:
        cache-name: cache-cabal
      with:
        path: |
          ${{ steps.cabal-setup.outputs.cabal-store }}
          dist-newstyle
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies
    - name: Build
      run: cabal build hapl --ghc-options=-O2
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        # Artifact name
        name: ${{ matrix.os }}-hapl # optional, default is github-pages
        # Path of the directory containing the static assets.
        path: | # default is _site/
          dist-newstyle/build/*/*/*/*/hapl/build/hapl/hapl
          dist-newstyle/build/*/*/*/*/hapl/build/hapl/hapl.exe
        # Duration after which artifact will expire in days.
        retention-days: 100 # optional, default is 1
